---
- hosts: routers
  become: yes
  gather_facts: no

  tasks:
    - name: Default interfaces
      cisco.ios.ios_config:
        lines: 
        - shutdown
        - default interface {{ item.int_name }}
        parents: interface {{ item.int_name }}
      with_items: "{{ interfaces.Data }}"
